const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT || 465),
  secure: process.env.SMTP_SECURE !== "false", // true for port 465
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

async function sendEmail({ to, subject, html, text }) {
  await transporter.sendMail({
    from: process.env.EMAIL_FROM,
    to,
    subject,
    text,
    html,
  });
}

function otpEmailTemplate(otp, purpose) {
  const action = purpose === "register" ? "complete your registration" : "log in";
  return {
    subject: `Your OTP code: ${otp}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 480px; margin: auto;">
        <h2 style="color:#1f2937;">Landslide Early Warning System</h2>
        <p>Use the code below to ${action}. It expires in ${process.env.OTP_EXPIRY_MINUTES || 5} minutes.</p>
        <p style="font-size: 32px; font-weight: bold; letter-spacing: 6px; color:#b45309;">${otp}</p>
        <p style="color:#6b7280; font-size: 13px;">If you did not request this, you can safely ignore this email.</p>
      </div>
    `,
    text: `Your OTP code is ${otp}. It expires in ${process.env.OTP_EXPIRY_MINUTES || 5} minutes.`,
  };
}

function disasterAlertTemplate({ locationName, latitude, longitude, riskLabel, probability }) {
  const probLine =
    probability !== null && probability !== undefined
      ? `<p><strong>Model confidence:</strong> ${(probability * 100).toFixed(1)}%</p>`
      : "";
  return {
    subject: `⚠️ Landslide Risk Alert: ${locationName || `${latitude}, ${longitude}`}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 520px; margin: auto; border: 1px solid #fca5a5; border-radius: 8px; padding: 20px;">
        <h2 style="color:#b91c1c;">Landslide Risk Alert</h2>
        <p>The prediction system has classified the following location as <strong>${riskLabel}</strong>.</p>
        <p><strong>Location:</strong> ${locationName || "Unnamed location"}</p>
        <p><strong>Coordinates:</strong> ${latitude}° N, ${longitude}° E</p>
        ${probLine}
        <p>Please verify ground conditions and take appropriate disaster-management action per local protocol.</p>
        <p style="color:#6b7280; font-size:12px;">This is an automated alert generated by the SIH Landslide Early Warning platform.</p>
      </div>
    `,
    text: `Landslide risk alert: ${locationName || `${latitude}, ${longitude}`} classified as ${riskLabel}.`,
  };
}

module.exports = { sendEmail, otpEmailTemplate, disasterAlertTemplate };
